# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87a7533b983b81e650c6797ff1897ffe25b94cb25e0de9b971286fb517afd8d2ac435080e037f94edafc692c7dc436ae58c1a0571ff1c72af76369d7b6f439d9

test:
  secret_key_base: 7e78d740e07f20d1b29224b05c26762c3cc7e38b3b3815cd7081690b070c848bfb9e61f93adc78301f4e904f0a34dc112e0ea95edfcc22d78110d3389d425ace

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
